name: Auto publish updated npm packages
on:
  push:
    branches: [main]
  # pull_request:
  #   types: [closed]

jobs:
  publish:
    # if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    name: Auto publish to npm
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./packages/dhruv-1', './packages/dhruv-2'] }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with: 9.0.3

          
      - name: Install dependencies
        run: pnpm install

      - name: Semantic Release for npm package
        working-directory: ${{ matrix.dir }}
        run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
